Settings:
  Prefix: '&7[&cCrazyEnvoy&7]: ' #The prefix before the messages CrazyEnvoys sends.
  Falling-Block: '138' #The block that will be falling.
  Max-Crate-Toggle: false #If ture then only a specified amount of crates will spawn and if false then all crates will spawn.
  Max-Crates: 20 #The max amount of crates that will spawn.
  Envoy-Run-Time: '5m' #The amount of time the envoy event will go for.
  Envoy-Cooldown: '1h' #The time till the envoy event will happen again.
  Minimum-Players-Toggle: false #When the envoy is about to start toggle if there needs to be a minimum amount of players. (Does not affect flares)
  Minimum-Players: 12 #The minimum amount of players needed to start the envoy.
  Envoy-Warnings: #The times that will make the warning messages.
    - '30m'
    - '15m'
    - '10m'
    - '1m'
    - '30s'
    - '20s'
    - '10s'
    - '5s'
    - '3s'
    - '1s'
  Flares: #Options about flares. Players need the crazyenvoy.flare.use permission to use the flares.
    Item: '76' #The time the flares are.
    Name: '&7&l(&4&l!&7&l) &cFlare' #The name of the flare.
    Lore: #The lore of the flare.
      - '&7Right click me to'
      - '&7start an envoy event.'