name: CrazyEnvoy
author: BadBones69
main: me.BadBones69.envoy.Main
version: 1.2.1
description: A crazy envoy plugin.
softdepend: [HolographicDisplays]
commands:
  envoy:
    description: Shows the next time till the next envoy.