name: CrazyEnvoy
author: BadBones69
main: me.BadBones69.envoy.Main
version: 1.2.6
description: A crazy envoy plugin.
softdepend: [HolographicDisplays, PlaceholderAPI, MVdWPlaceholderAPI, Multiverse-Core, MultiWorld]
commands:
  envoy:
    description: Shows the next time till the next envoy.