name: CrazyEnvoy
author: BadBones69
main: me.BadBones69.envoy.Main
version: 1.2.4.2
description: A crazy envoy plugin.
softdepend: [HolographicDisplays, PlaceholderAPI, MVdWPlaceholderAPI]
commands:
  envoy:
    description: Shows the next time till the next envoy.